# Generated by Django 5.0.1 on 2024-01-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='brand',
        ),
    ]
