# Generated by Django 5.0.1 on 2024-01-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_category_desciption_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cat',
        ),
    ]
