# Generated by Django 5.0.1 on 2024-01-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_category_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggestion',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
