# Generated by Django 3.2.12 on 2024-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suggestion',
            field=models.ManyToManyField(related_name='_products_product_suggestion_+', to='products.Product'),
        ),
    ]
