# Generated by Django 5.0.1 on 2024-01-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suggestion',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
